### ISSUE TITLE
Flutter tags for asset catalog filtration

### ISSUE THREAD

**Issue by jdharvey-ibm** [carbon-design-system/carbon-platform#69] opened 2021-11-08 16:47 UTC
### Summary

As per the design specs, we want to use flutter tags as the means of filtration and visualization in the asset catalogs on the carbon platform.

**Comment by mattrosno** [comment] 2021-12-14 17:53
Duplicate of https://github.com/carbon-design-system/carbon-platform/issues/32

**Closed by mattrosno** 2021-12-14 17:53 UTC
Labels: role: dev 🤖, role: visual 🎨, type: enhancement 💡
