### ISSUE TITLE
Library Assets Page: make "library maintainers" a link

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon-platform#522] opened 2022-04-08 00:53 UTC
Redline: https://ibm.ent.box.com/file/913340274022
Can't do this until we figure out where/if we're going to have maintainers/contributors section in-app (ongoing discussion)

**Comment by mattrosno** [comment] 2022-04-18 17:56
Closing this as a duplicate of https://github.com/carbon-design-system/carbon-platform/issues/295

**Closed by mattrosno** 2022-04-18 17:56 UTC
Labels: role: dev 🤖, status: blocked 🙅‍♀️
